
### Date: 2025-09-01
- Practiced C and stumbled across bit manipulation. It was a nice opportunity to go deeper. Ended up writing an article describing them with respect to 8-bit registers.
  Learnt a bunch of things along the way. See this for more details [Bit manipulation notes](../entries/bit_manipulation_in_8_bit_registers.qmd)
- Fixed a project I can do in C: Building a HTTP Server. But first need to understand what we are building. Started jotting down some thoughts here
  [Building a HTTP server in C](../entries/http_server.qmd)

### Date: 2025-08-31
- Looked deeply in URDFs and their structure, came across URDF creator tool which seemed promising.
- Compared various FK python libraries (urdfpy, urdf2casadi, pytorch_kinematics, pinnochio). See [fk_in_python](../entries/fk_in_python.qmd)
- Refreshed conda basics, and practiced creating new environments over and over gain. As a refresher see this [conda_basics](../entries/conda_basics.qmd)


### Date: 2025-08-30

- Revised chapter 1, and wrote detailed [notes](../entries/chapter_1_spong_notes.qmd)
- Started writing notes for Forwardk kinematics [notes](../entries/forward_kinematics.qmd)
    - Denavit–Hartenberg parameters took some time to understand, but in the end the realized that URDF to FK is probably more important.

### Date: 2025-08-24

- Read through Chatper 1: Introduction to Robotics of "Robot Modelling and control" by Spong
- Spent a bunch of time figuring out the correct format to log notes to github.
- Experimented with Jekyll and Hugo, both of which sucked at rendering LaTex
- Finally after much experimentation Quarto seemed like a good option
- This is a sample file using quarto's math rendering [link](../test/math.qmd)
