---
title: Notes from Technical writing course - Google
description: "***Last updated***: 2025-09-07"
format: html
---

Source: [https://developers.google.com/tech-writing/one](https://developers.google.com/tech-writing/one)

## Key takeaways:

1. Make sure its easy to identify the nouns associated with your pronouns.
2. Prefer active voice over passive voice.
3. Aim for clear sentences.
    3.1 Choose strong verbs 
    3.2 Reduce there is / there are
    3.3 Minimize certain adjectives and verbs
4. Aim for Short sentences.
    4.1 Break up long sentences into shorter ones.
    4.2 Convert some longer sentences to lists.
    4.3 Eliminate or reduce extranoues words.
    4.4 Reduce subordinate clauses.
    4.5 Which v/s That 
        - which is for non-important stuff, that is for important stuff.
        - place a comma before which, do not place a comma before that.
5. TODO: list and tables.

## Exercises:

Mark the following sentences as either Passive / active:

- MutableInput provides read-only access -- active
- Read-only access is provided by the MutableInput -- passive.
    - [Active] MutableInput provides read-only access.
- Performance was measured -- passive.
    - ?
- Python was invented by Guido Van Rossum in the twentieth century -- passive.
    - [Active] Guido Van Rossum invented python in the twentieth century.
- David Korn discovered the KornShell quite by accident -- active.
- This information is used by the polic enforcement team -- passive.
    - [Active] Police enforcement team uses the information.
- Click the submit button -- active.
- The orbit was calculated by Katherine Johnson -- passive.
    - [Active] Katherine Johnson calculated the orbit.

**Categorize which verbs are active / passive.**

- The QA team loves ice cream, but the writes prefer sorbet:
    - Active, Active
- Performance metrics are required by the team, though I prefer wild guesses.
    - Passive, Active,
    - The team requires performance metrics, though I pefere wild guesses.
- When software engineers attempt something new and innovative, a reward should be given.
    - Active, Passive.
    - When software engineers attempt something new and innovative, they should be given a reward.

**Rewrite the following passive voices into active voice:**

- The flags weren't parsed by the Mungifier
    - Mungifier didn't parse the flags.
- A wrapper is generated by the Op registration process.
    - The Op registration process generates a wrapper.
- Only one experiment per layer is selected by the Frombus system.
    - The Frombus system selects only one experiment per layer.
- Quality metrics are identified by asterisks; ampersands identify bad metrics.
    - Asterisks identify quality matrics; ampersands identify bad metrics.


**Examples of weak/strong verb**

- Weak: The exception *occurs* when dividing by zero.
  - Strong: Dividing by zero *raises* the exception.
- Weak: This error message *happens* when..
  - Strong: The system *generates* this error when..
- Weak: We *are* very carefuly to ensure...
  - Strong: We carefully ensure...

**Clarify the sentences by picking more specific verbs**

- When a variable declaration doesn't have a datatype, a compiler error happens.
    - Compiler raises an error, when a variable declaration is missing a datatype.
- Compiler error occurs when you leave off a semicolon at the end of a statement.
    - Compiler raises an error, when a statement is missing a semicolon.

**Clarify these sentences by removing there is**

- There is a lot of overlap between X and Y.
    - X and Y overlap a lot.
- There is no creator stack for the main thread.
    - The main thead does not provide a creator stack.
- There is a low-level, tensorflow, python interface to load a saved model.
    - tensorflow provides a low-level python interface to load a saved model.
- There is a sharding function named `distribute` that assigns keys.
    - A sharding function named `distribute` assigns keys.
    - The `distribute` sharding function assigns keys.

**Convert this long sentence to shorter sentnces. don't revise too much**

In bash, use the if, then, and fi statements to implement a simple conditional
branching block in which the if statement evaluates an expression, the then statement
introduces a block of statements to run when the if expression is true, and the fi
statement marks the end of the conditional branching block.

- In bash, use the if, then and fi statements to implement a simple conditional branching
  block. `If` statements evaluates an expression. `Then` statement introduces a block of 
  statements, when the `if` expression is true. `Fi` statement marks the end of the
  conditional branching block.

NOTE: Above is still unclear but is much easier to read than the original sentence.

**Simplify this function**

To alter the usual flow of a loop, you may use either a break statement (which hops you out of 
the current loop) or a continue statement (which skips past the remainder of the current 
iteration of the current loop).

- To alter the usual flow of a loop, you may use:
   - Either a break statement, which hops you out of the current loop.
   - Or a continue statement, which skips past the remainder of the current iteration of the current loop.


**As an exercise refactor the following setences**

To get start with the Frambus app, you must fist find the app at a suitable store,
pay for it using a valid credit card or debit card, download it, configure it by assigning
a value for `Foo` variable in the `/etc/Frambus` file, and then run it by saying the magic word twice.

Follow these steps, to get started with the `Frambus` app:
- Find the app at a suitable store.
- Pay for the app using a valid credit/debit card.
- Download the app.
- Configure the app by assigning a value for the `Foo` variable in the `/etc/Frambus` file.
- Run the app by saying the magic word twice.


Kornshell was invented by David Korn in 1983, then a computer scientist at Bell
Labs, as a superset of features, enhancements, and improvements over the Bourne shell
(which it was backwards compatible with), which was invented by Stephen Bourne in 1977 who was 
also a computer scientist at Bell Labs.

- David Korn, a computer scientist at Bell labs, invented the KornShell in 1983.
- Kornshell offered features, enhancements and improvements over the Bourne Shell.
- Kornshell was backwards compatible with Bourne shell.
- Stephen Bourne, who was alos a computer scientist at Bell labs. invented the Bourne Shell in 1977,

**Eliminate or reduce extraneous words**

Some examples:

An input value greater than 100 causes the triggering of logging.
- An input value greater than 100 triggers logging.

This design document provides a detailed description of Project Frambus.
- This design document describes Project Frambus.

In spite of the fact that Arnold writes buggy code, he writes error-free documentation
- Although Arnold writes buggy code, he writes error-free documentation.

Changing the sentence from passive voice to active voice enhances the clarification of the key points.
- Changing the sentences from passive voice to active voice, clarifies the key points.

Determine whether Rikona is able to write code in COBOL.
- Determine whether Rikona can code in COBOL.

Frambus causes the production of bugs, whhich will be chronicled in logs by the LogGenerator method.
- Frambus produces bugs, which will be logged by the LogGenerator method. -- first reduce the extra words
- Frambus produces bugs, which the LogGenerator method logs -- second change from passive to active.


**Determine subordinate clauses below, and decide which clauses can be branched off**

- Python is an interepreted language, which manes that the languate can execute source code directly.
    - Extends the idea, so okay to keep.
- Bash is a modern shell scripting language that takes many of its features from the Kornshell 88, which was developded at bell labs.
    - Idea 1: Bash is a modern shell scripting language: main clause
    - Idea 2: Bash takes many of tis features from the KornShell 88 -- subclause, extends the idea. can be kept.    
    - Idea 3: Bash was developed at Bell labs -- subidea, can be branched off.

- Lisp is a programming language that relies on polish prefix notation, which is one of the systems 
  invented by the Polish logician Jan Luka.
    - Idea 1: Lisp is a programming language -- main clause.
    - Idea 2: that relies on polish prefix notation -- okay to keep.
    - Idea 3: which is one of the systems invented by the Polis... -- can be branched off.

- I don't want to say that Fortran is old, but only radiocarbon dating can determine its true age.
    - Idea 1: I don't way to say the fortran is old: main clause
    - Idea 2: but only radiocarbon dating can determine.. - subclause, but critical to the meaning of the sentence.